name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check code formatting using gofmt
      uses: Jerome1337/gofmt-action@v1.0.4
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout
      run: git fetch --prune --unshallow --tags
      
    - name: Development Docker
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker info
        docker buildx create --name builder --use
        docker buildx inspect --bootstrap
        docker buildx ls
        docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile --push --output=type=image,name=tweeticoats/xbvr:develop,push=true .
